# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/consulting_proposals" do
  let(:current_user) { create(:user, role: "admin") }
  let(:consulting) { create(:consulting) }
  let(:valid_attributes) { attributes_for(:consulting_proposal, consulting_id: consulting.id) }

  let(:invalid_attributes) { attributes_for(:consulting_proposal, consulting_id: nil) }

  let(:valid_headers) do
    { Authorization: "Bearer #{current_user.token}" }
  end

  describe "GET /index" do
    it "renders a successful response" do
      ConsultingProposal.create! valid_attributes
      get api_v1_consulting_proposals_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      consulting_proposal = ConsultingProposal.create! valid_attributes
      get api_v1_consulting_proposal_url(consulting_proposal), as: :json, headers: valid_headers
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ConsultingProposal" do
        expect do
          post api_v1_consulting_proposals_url,
               params: { consulting_proposal: valid_attributes }, headers: valid_headers, as: :json
        end.to change(ConsultingProposal, :count).by(1)
      end

      it "renders a JSON response with the new api_v1_consulting_proposal" do
        post api_v1_consulting_proposals_url,
             params: { consulting_proposal: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ConsultingProposal" do
        expect do
          post api_v1_consulting_proposals_url,
               params: { consulting_proposal: invalid_attributes }, as: :json
        end.not_to change(ConsultingProposal, :count)
      end

      it "renders a JSON response with errors for the new api_v1_consulting_proposal" do
        post api_v1_consulting_proposals_url,
             params: { consulting_proposal: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested api_v1_consulting_proposal" do
        consulting_proposal = ConsultingProposal.create! valid_attributes
        patch api_v1_consulting_proposal_url(consulting_proposal),
              params: { consulting_proposal: new_attributes }, headers: valid_headers, as: :json
        consulting_proposal.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the api_v1_consulting_proposal" do
        consulting_proposal = ConsultingProposal.create! valid_attributes
        patch api_v1_consulting_proposal_url(consulting_proposal),
              params: { consulting_proposal: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the api_v1_consulting_proposal" do
        consulting_proposal = ConsultingProposal.create! valid_attributes
        patch api_v1_consulting_proposal_url(consulting_proposal),
              params: { consulting_proposal: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested api_v1_consulting_proposal" do
      consulting_proposal = ConsultingProposal.create! valid_attributes
      expect do
        delete api_v1_consulting_proposal_url(consulting_proposal), headers: valid_headers, as: :json
      end.to change(ConsultingProposal, :count).by(-1)
    end
  end
end
