# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
RSpec.describe "/api/v1/consultings" do
  let(:client) { create(:user, phone: "(61) 99999-9999") }
  let(:consultant) { create(:user, phone: "(61) 99999-9999") }
  let(:consulting) { create(:consulting) }

  let(:valid_attributes) do
    {
      client:,
      consultant:,
      status:     :not_started,
      value:      1000.0
    }
  end

  let(:invalid_attributes) do
    {
      client:     nil,
      consultant: nil,
      status:     nil,
      value:      -1.0
    }
  end

  let(:valid_headers) do
    { Authorization: "Bearer #{consultant.token}" }
  end

  describe "POST /import" do
    let(:consulting) { create(:consulting, client: nil, import_hash: "123456") }

    let(:valid_headers) do
      { Authorization: "Bearer #{client.token}" }
    end

    it "updates the consulting client_id and returns status ok" do
      post "/api/v1/consultings/#{consulting.import_hash}/import", headers: valid_headers, as: :json

      expect(response).to have_http_status(:ok)

      consulting.reload

      expect(consulting.client_id).to eq(client.id)
    end

    it "raises ActiveRecord::RecordNotFound if consulting is not found" do
      post "/api/v1/consultings/invalid_hash/import", headers: valid_headers, as: :json

      expect(response).to have_http_status(:not_found)
    end
  end
end
