# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/institutions" do
  let(:current_user) { create(:user, phone: "(61) 99999-9999") }
  let(:institution) { create(:institution) }
  let(:valid_attributes) { attributes_for(:institution, phone: "(61) 9999-9999", cell_phone: "(61) 99999-9999") }
  let(:invalid_attributes) { { email: "", phone: "" } }
  let(:new_attributes) { { email: "new@email.com.br" } }

  let(:valid_headers) do
    { Authorization: "Bearer #{current_user.token}" }
  end

  describe "GET /index" do
    it "renders a successful response" do
      Institution.create! valid_attributes
      get api_v1_institutions_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      institution = Institution.create! valid_attributes
      get api_v1_institution_url(institution), as: :json, headers: valid_headers
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Institution" do
        expect do
          post api_v1_institutions_url,
               params: { institution: valid_attributes, user: attributes_for(:user, phone: "(61) 9999-9999") }, headers: valid_headers, as: :json
        end.to change(Institution, :count).by(1)
      end

      it "renders a JSON response with the new institution" do
        post api_v1_institutions_url,
             params: { institution: valid_attributes, user: attributes_for(:user, phone: "(61) 9999-9999") }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Institution" do
        expect do
          post api_v1_institutions_url,
               params: { institution: invalid_attributes }, as: :json
        end.not_to change(Institution, :count)
      end

      it "renders a JSON response with errors for the new institution" do
        post api_v1_institutions_url,
             params: { institution: invalid_attributes, user: attributes_for(:user) }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested institution" do
        institution = Institution.create! valid_attributes
        patch api_v1_institution_url(institution),
              params: { institution: new_attributes }, headers: valid_headers, as: :json
        institution.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the institution" do
        institution = Institution.create! valid_attributes
        patch api_v1_institution_url(institution),
              params: { institution: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the institution" do
        institution = Institution.create! valid_attributes
        patch api_v1_institution_url(institution),
              params: { institution: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested institution" do
      institution = Institution.create! valid_attributes
      expect do
        delete api_v1_institution_url(institution), headers: valid_headers, as: :json
      end.to change(Institution, :count).by(-1)
    end
  end
end
