# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users" do
  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:current_user) { create(:user, phone: "(61) 9999-9999") }
  let(:user) { create(:user, phone: "(61) 9999-9999") }
  let(:valid_attributes) { attributes_for(:user, phone: "(61) 9999-9999") }
  let(:invalid_attributes) { { email: "", name: "", password: "" } }
  let(:new_attributes) { { email: "new@email.com.br", name: "new", password: "321321", password_confirmation: "321321" } }

  let(:valid_headers) do
    { Authorization: "Bearer #{current_user.token}" }
  end

  describe "GET /index" do
    it "renders a successful response on index" do
      get "/api/v1/users", headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response on show" do
      get "/api/v1/users", headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new User" do
        current_user
        expect do
          post "/api/v1/users",
               params: { user: valid_attributes }, headers: valid_headers, as: :json
        end.to change(User, :count).by(1)
      end

      it "renders a JSON response with the new user" do
        post "/api/v1/users",
             params: { user: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new User" do
        current_user
        expect do
          post "/api/v1/users",
               params: { user: invalid_attributes }, headers: valid_headers, as: :json
        end.not_to change(User, :count)
      end

      it "renders a JSON response with errors for the new user" do
        post "/api/v1/users",
             params: { user: invalid_attributes }, headers: valid_headers, as: :json

        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      it "updates the requested user" do
        patch "/api/v1/users/#{user.id}",
              params: { user: new_attributes }, headers: valid_headers, as: :json
        user.reload
        expect(user.email).to eq(new_attributes[:email])
      end

      it "renders a JSON response with the user" do
        patch "/api/v1/users/#{user.id}",
              params: { user: new_attributes }, headers: valid_headers, as: :json

        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the user" do
        patch "/api/v1/users/#{user.id}",
              params: { user: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user" do
      current_user
      user = create(:user, phone: "(61) 9999-9999")
      expect do
        delete "/api/v1/users/#{user.id}", headers: valid_headers, as: :json
      end.to change(User, :count).by(-1)
    end
  end
end
