import 'package:flutter/material.dart';

final List<DropdownMenuItem<String>> dropdownItemsStatesBrasil = [
  const DropdownMenuItem(value: 'AC', child: Text('Acre')),
  const DropdownMenuItem(value: 'AL', child: Text('Alagoas')),
  const DropdownMenuItem(value: 'AP', child: Text('Amapá')),
  const DropdownMenuItem(value: 'AM', child: Text('Amazonas')),
  const DropdownMenuItem(value: 'BA', child: Text('Bahia')),
  const DropdownMenuItem(value: 'CE', child: Text('Ceará')),
  const DropdownMenuItem(value: 'DF', child: Text('Distrito Federal')),
  const DropdownMenuItem(value: 'ES', child: Text('Espírito Santo')),
  const DropdownMenuItem(value: 'GO', child: Text('Goiás')),
  const DropdownMenuItem(value: 'MA', child: Text('Maranhão')),
  const DropdownMenuItem(value: 'MT', child: Text('Mato Grosso')),
  const DropdownMenuItem(value: 'MS', child: Text('Mato Grosso do Sul')),
  const DropdownMenuItem(value: 'MG', child: Text('Minas Gerais')),
  const DropdownMenuItem(value: 'PA', child: Text('Pará')),
  const DropdownMenuItem(value: 'PB', child: Text('Paraíba')),
  const DropdownMenuItem(value: 'PR', child: Text('Paraná')),
  const DropdownMenuItem(value: 'PE', child: Text('Pernambuco')),
  const DropdownMenuItem(value: 'PI', child: Text('Piauí')),
  const DropdownMenuItem(value: 'RJ', child: Text('Rio de Janeiro')),
  const DropdownMenuItem(value: 'RN', child: Text('Rio Grande do Norte')),
  const DropdownMenuItem(value: 'RS', child: Text('Rio Grande do Sul')),
  const DropdownMenuItem(value: 'RO', child: Text('Rondônia')),
  const DropdownMenuItem(value: 'RR', child: Text('Roraima')),
  const DropdownMenuItem(value: 'SC', child: Text('Santa Catarina')),
  const DropdownMenuItem(value: 'SP', child: Text('São Paulo')),
  const DropdownMenuItem(value: 'SE', child: Text('Sergipe')),
  const DropdownMenuItem(value: 'TO', child: Text('Tocantins')),
];
